---
mariadb_server_package_name: mariadb-server
mariadb_packages:
  - "{{ mariadb_server_package_name }}"
  - "{{ mariadb_build_slave | bool | ternary('percona-xtrabackup-24', '') }}"
  - "{{ ansible_python_version | default('3') is version('3', '<') | ternary('python-mysqldb', 'python3-pymysql') }}"
  - qpress
  - mytop
mariadb_service_name: mysql
mariadb_service_user: mysql
mariadb_service_group: mysql

mariadb_deb_repository: "deb [arch=amd64] https://ftp.igh.cnrs.fr/pub/mariadb/repo/10.5/debian {{ ansible_distribution_release }} main"
mariadb_apt_key_server: hkp://keyserver.ubuntu.com:80
mariadb_apt_key_id: "0xF1656F24C74CD1D8"
mariadb_mysql_apt_key_id: "5072E1F5"

mariadb_mysql_apt_deb_filename: mysql-apt-config_0.8.13-1_all.deb
mariadb_mysql_apt_deb: "https://dev.mysql.com/get/{{ mariadb_mysql_apt_deb_filename }}"
mariadb_mysql_apt_deb_target_path: "/tmp/{{ mariadb_mysql_apt_deb_filename }}"
mariadb_mysql_version: mysql-8.0

mariadb_percona_apt_deb_filename: "percona-release_1.0-9.generic_all.deb"
mariadb_percona_apt_deb: "https://repo.percona.com/apt/{{ mariadb_percona_apt_deb_filename }}"
mariadb_percona_apt_deb_target_path: "/tmp/{{ mariadb_percona_apt_deb_filename }}"

mariadb_root_mycnf_filepath: /root/.my.cnf
mariadb_etc_path: /etc/mysql
mariadb_mycnf_path: "{{ mariadb_etc_path }}/my.cnf"
mariadb_socket: /var/run/mysqld/mysqld.sock
mariadb_data_path: /var/lib/mysql
mariadb_ssh_key_filepath: /root/.ssh/id_rsa
mariadb_ssh_public_key_filepath: "{{ mariadb_ssh_key_filepath }}.pub"
mariadb_tmp_local_ssh_public_key_filepath: /tmp/mariadb-id_rsa.pub

mariadb_mycnf:
  mysqld:
    # Set binlog format (row, mixed, statement)
    # https://mariadb.com/kb/en/mariadb/binary-log-formats
    binlog_format: 'mixed'
    bind-address: '0.0.0.0'
    character-set-server: 'utf8'
    init-connect: 'SET NAMES utf8'
    collation-server: utf8_unicode_ci
  client:
    default-character-set: 'utf8'
  mysql:
    default-character-set: 'utf8'

mariadb_build_slave: false
mariadb_slave_replication: true
mariadb_root_password: CHANGEME
mariadb_replicate_username: repl
mariadb_replicate_password: CHANGEME
mariadb_decompress_memory: 1G

# Sample to add users
# mariadb_users:
#   - username: user1
#     password: pass1
#     host: localhost
#     priv: db1.*:ALL
#   - username: user2
#     password: pass2
#     host: '%'
#     priv: *.*:ALL

# Sample to create databases
# mariadb_databases:
#   - db1
#   - db2

mariadb_bind_address: '0.0.0.0'
mariadb_extra_configuration:
  innodb_commit_concurrency: 0
mariadb_use_percona_apt: false
mariadb_install_xtrabackup_package: false
mariadb_slow_query_log_enabled: true

mariadb_use_galera: true
mariadb_galera_members:
  - '{% if is_docker %}docker-{% else %}vbox-{% endif %}{{ ansible_distribution_release }}-upstream-galera-1'
  - '{% if is_docker %}docker-{% else %}vbox-{% endif %}{{ ansible_distribution_release }}-upstream-galera-2'
  - '{% if is_docker %}docker-{% else %}vbox-{% endif %}{{ ansible_distribution_release }}-upstream-galera-3'

mariadb_replication_master: false
mariadb_replication_slave: true
mariadb_replication_user: 'replication'
mariadb_replication_password: '1a2b3c'
mariadb_server_id: 2
mariadb_slave_ignore_db: ['norepl']

# vim: set ft=yaml :

  